SEED = 1234
NUMBER_OF_FOG_NODES = 2
NUMBER_OF_EDGE_NODES = 4
NUMBER_OF_CLOUD_NODES = 1

MAX_EDGE_CPU_FREQUENCY = 1.5
MIN_EDGE_CPU_FREQUENCY = 0.5

MAX_FOG_CPU_FREQUENCY = 2.5
MIN_FOG_CPU_FREQUENCY = 1.6

MAX_CLOUD_CPU_FREQUENCY = 3.5
MIN_CLOUD_CPU_FREQUENCY = 2.6
